// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWNHzIA2xNNRF0zDT95efJrgU9egEib4',
    appId: '1:114484576974:web:726a6c74b8b95a69f0069f',
    messagingSenderId: '114484576974',
    projectId: 'lensofblessings',
    authDomain: 'lensofblessings.firebaseapp.com',
    storageBucket: 'lensofblessings.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbPKDJzuzobuyrgayxQNmT7v9-8nZBYBA',
    appId: '1:114484576974:android:7729b8576692b20ef0069f',
    messagingSenderId: '114484576974',
    projectId: 'lensofblessings',
    storageBucket: 'lensofblessings.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRevKgT7btnQGzn2jTorqw8_Bpqk5FrU',
    appId: '1:114484576974:ios:ce6419db1c4d56a3f0069f',
    messagingSenderId: '114484576974',
    projectId: 'lensofblessings',
    storageBucket: 'lensofblessings.firebasestorage.app',
    iosBundleId: 'com.example.lensOfBlessings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvRevKgT7btnQGzn2jTorqw8_Bpqk5FrU',
    appId: '1:114484576974:ios:ce6419db1c4d56a3f0069f',
    messagingSenderId: '114484576974',
    projectId: 'lensofblessings',
    storageBucket: 'lensofblessings.firebasestorage.app',
    iosBundleId: 'com.example.lensOfBlessings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAWNHzIA2xNNRF0zDT95efJrgU9egEib4',
    appId: '1:114484576974:web:c16d0662476f7862f0069f',
    messagingSenderId: '114484576974',
    projectId: 'lensofblessings',
    authDomain: 'lensofblessings.firebaseapp.com',
    storageBucket: 'lensofblessings.firebasestorage.app',
  );
}
